apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mzior7jj3-python
  janus-idp.io/tekton: mzior7jj3-python
  backstage.io/kubernetes-id: mzior7jj3-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mzior7jj3-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
